### PR TITLE
resolves #126 automagically create a `.keep` file when user commits an empty directories

### LINKED ISSUE #126: Support Empty directories
`Command execution error: svn: E200015: Empty directories is not supported: /Page/a0`

i think it can create `.keep` in Empty directories

### PR DESCRIPTION
**Pull request by slonopotamus**
closes #339

### CODE REVIEW

**Comment by slonopotamus** [comment]
The problem with this approach is that it does **not** work.

Scenario:

1. `svn checkout`
2. `svn add <dir>`
3. `svn commit`
4. `svn update`
5. Look for `.keep` file in `<dir>`. Whoops. git-as-svn created `.keep` file on step 3. But svn client doesn't know about that and believes that he already has up-to-date dir. So `svn update` on step 4 does **not** create `.keep` file in working copy. So, client view of repository state is now inconsistent with server view and client will break in various ways from here onwards.

**Comment by slonopotamus** [comment]
Closing, it is not going to be merged due to reasons specified above.

**Comment by MichaelJCole** [comment]
If the svn commit made 2 git commits, but git-as-svn returned only the first git commit as the svn version number:  

1) git commit everything else.  Return this version to the svn client
2) git commit the .keep file

Then, when the client:
- updated, it would pull revision 2.  
- committed, it would see rev 2 and ask to update.

This patch doesn't do that, but it's a start.

There is an edge case where the only thing committed are empty directories, and that seems like it could just fail like it does now.

**Comment by slonopotamus** [comment]
I don't see how that dodges the need to somehow store info about empty directory existence in first of the two commits in git-as-svn. svn user can later update to this commit at any moment.

**Comment by MichaelJCole** [comment]
Git<->Svn isn't a perfect mapping, so the empty directory info is valid Svn, but invalid git.  But we can deliver the user's Svn intent with 2 Git commits.

We just ignore empty directories for the first commit.  Git doesn't do empty directories.  Return this commit to the user so SVN client stays consistent.

The 2nd commit is as if someone else added their keep files after their commit.  They have to update to get them.  Another option would be to drop the directories as if nothing happened.  For me when I hit this problem it's because I clicked "All" in TortoiseSVN.

It could be an optional feature in the .conf file.  
OnCommitEmptyDirectory = Fail | Ignore | CreateKeepFileIn2ndCommit

**Comment by bwegh** [comment]
I agree with the comments about the inconsistency between git and svn when adding an empty directory.

This is due to the fact that a file is added as it is needed by git.

The question is does this cause harm if git-as-svn removes it as soon as one file is added to the directory?

I did add it to your solution like this: 
https://github.com/bwegh/git-as-svn/commit/ce7500b315823cd61c58ca182c9632039e5535a0

It works very well for my use case, maybe it is worth a look - esp. I did not find out how to validate the content of the .keep file.

and then adding the configuration @MichaelJCole  proposes.

**Comment by MichaelJCole** [comment]
re: Does it cause harm?  Probably not - as long as git-as-svn knows it put the file there.  Checking the file contents for a message like "git-as-svn created this file ..."  before deleting would work.  Crufty files are an inconvenience.

What happens if svn client deletes a file, but leaves an empty directory?  This would be another use case for creating the .keep file or deleting the directory.  Either way a second commit would make the svn client consistent again.

**Comment by bwegh** [comment]
currently the commit above creates a .keep file if the directory is empty, either newly created or all content removed.

I agree that those files are inconvenience.

I use an application that runs multiple svn commits in a batch: 

1. creates an empty directory with one svn commit 
2. adds content into the previously created folder in multiple commits

Would that work with adding the .keep file in a 2nd git commit?
I assume you need an svn up before adding the content to the directory in the example above, or?

**Comment by slonopotamus** [comment]
> The question is does this cause harm if git-as-svn removes it as soon as one file is added to the directory?

Yes, it does. It violates client assumptions about repository state. Please, reread https://github.com/bozaro/git-as-svn/pull/340#issuecomment-609044368. Client believes that if he tried to commit an empty dir and succeeded in revision N, then in that revision N directory *is* empty. There's no way in SVN protocol to explain client that his information about directory state in that revision is wrong.

**Comment by bwegh** [comment]
so I do understand that the svn clients has two assumptions:
1. the directory is committed
2. the directory is empty

Is it possible to commit the directory to git without violating the 2nd assumption?
Is it better to not commit empty directories and which violates assumption no 1?

Are there other options on how to commit an empty directory?

**Comment by slonopotamus** [comment]
> the svn clients has two assumptions

Actually, it is a single assumption that states something like this:

If client has some something (file/directory) that has a revision number assigned by server, client assumes that this thing is exactly the same on server _for that revision number_. For files, "same" means contents + svn properties. For directories, "same" means list of direct descendants + svn of properties.

Emphasized part is important. It means that git-as-svn can commit anything additionally to the files user is trying to commit as long as it doesn't interfere with what user is actually committing.

Unfortunately, for empty dirs it means that we cannot add anything to them and would need to store info about empty dir existence _elsewhere_. Like, dunno, `/.empty-dirs` file at repo root. But this route feels really awkward.

I failed to invent anything better given the constraints that svn client implies.

**Comment by MichaelJCole** [comment]
It's an awkward problem :-)  

Putting all the awkward in one file seems less complex than multiple files/commits or the commit error.  

I think it's a great solution, but I don't have a patch :-(

**Comment by bwegh** [comment]
do I understand correctly that the idea is to keep track of empty directories in a file in the directory? Does this not also break the assumption of the svn client as the directory is actually not committed?

We are still using the fix with the '.keep' file in empty directories, the .keep file is removed as soon as any other file is added by the svn client.

what are the differences between the two approaches? The first one is actually not committing the directory into the repository, instead it is altering a file. The 2nd approach is adding a marker file to be able to commit the directory to the repository and removes the file as soon as possible. In my opinion both approaches break the assumption of the svn client or did I miss something?

**Pull request closed without merging**
