### PR TITLE
Multiple platforms launcher support

### PR DESCRIPTION
**Pull request by fcharlie**
git-as-svn as a service,should add a launcher ,add start stop restart and status command 
So I create few files
launcher.bat & launcher.ps1 a launcher on windows
launcher a launcher on posix system
launcher.cfg launcher params ,a ini-format config file
launcher.vmoptions ,JVM start param

### CODE REVIEW

**Comment by bozaro** [comment]
Can one of the admins verify this patch?

**Comment by bozaro** [comment]
Can one of the admins verify this patch?

**Comment by bozaro** [comment]
Can one of the admins verify this patch?

**Comment by bozaro** [comment]
Can one of the admins verify this patch?

**Comment by bozaro** [comment]
The idea is good.
But before making a decision about these changes, I want to look like the problem is solved in the Jenkins.

**Comment by fcharlie** [comment]
@bozaro OK,In the Linux test is successful, Windows does not have ' through a registry query JDK installation path '

**Comment by fcharlie** [comment]
@bozaro  Now launcher.ps1 is test ok.Exception does not capture PowerShell

**Comment by slonopotamus** [comment]
We won't be taking this. On Windows, it is much more convenient to wrap git-as-svn into a windows service. On Linux, there are multiple incompatible init systems (OpenRC, SystemD, etc) and none of them will be able to utilize this initscripts as-is.

**Pull request closed without merging**
